name: alquranalkareem
description: Al-Quran Al-Kareem - Al-Heekmah Library.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.13+26

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  anim_search_bar: ^2.0.3
  animated_toggle_switch: ^0.6.2
  another_xlider: ^3.0.1
  arabic_numbers: ^1.0.0
  audio_session: ^0.1.16
  audioplayers: ^4.0.1
  bloc: ^8.1.2
  bot_toast: ^4.0.4
  clipboard: ^0.1.3
  connectivity_plus: ^4.0.1
  cool_dropdown: ^2.1.0
  cupertino_icons: ^1.0.2
  day_night_time_picker: ^1.2.0+2
  desktop_window: ^0.4.0
  dio: ^5.1.2
  dropdown_button2: ^2.3.7
  easy_image_viewer: ^1.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^14.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_screenutil: ^5.8.4
  flutter_sliding_up_panel: ^2.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.6
  get: ^4.6.5
  get_it: ^7.6.0
  group_button: ^5.3.0
  hijri: ^3.0.0
  home_widget: ^0.2.1
  html: ^0.15.3
  http: ^0.13.6
  image: ^4.0.17
  image_gallery_saver: ^1.7.1
  just_audio: ^0.9.34
  lottie: ^2.3.2
  package_rename: ^1.3.0
  painter: ^2.0.0
  path: ^1.8.3
  path_provider: ^2.0.15
  pixel_perfect: ^1.1.3
  quiver: ^3.2.1
  rate_my_app: ^2.0.0
  responsive_builder: ^0.7.0
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  share_plus: ^6.3.4
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  square_percent_indicater: ^0.1.0
  theme_provider: ^0.6.0
  url_launcher: ^6.1.11
  wakelock: ^0.6.1+1
  workmanager: ^0.5.1
#  scroll_to_index: ^3.0.1
dev_dependencies:
  build_runner: ^2.3.3
  flutter_native_splash: ^2.2.15
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#f3efdf"
  color_dark: "#2d2d2d"
  image: assets/app_icon.png
  image_dark: assets/app_icon.png

  android_12:
    image: assets/app_icon.png
    icon_background_color: "#f3efdf"
    image_dark: assets/app_icon.png
    icon_background_color_dark: "#2d2d2d"

package_rename_config:
  android:
    package_name: com.alheekmah.alquranalkareem.alquranalkareem

  ios:
    app_name: القرآن الكريم - مكتبة الحكمة
    package_name: com.alheekmah.alquranalkareem.alquranalkareem

    macos:
      app_name: القرآن الكريم مكتبة الحكمة
      package_name: com.alheekmah.alquranalkareem.alquranalkareem2

  flutter_lints: ^2.0.0

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/pages/
    - assets/svg/
    - assets/svg/surah_name/
    - assets/svg/juz/
    - assets/onboarding/
    - assets/images/
    - assets/svg/hijri/
    - assets/svg/alwaqf/
    - assets/svg/quarter/
    - assets/json/
    - assets/lottie/
    - assets/share_images/
    - assets/share_images/surah_name/
    - assets/QuranV3.sqlite
    - assets/QuranData.sqlite
    - assets/ayahinfo_1260.db
    - assets/app_icon.png

  fonts:
    - family: uthmanic
      fonts:
        - asset: assets/fonts/UthmanTN1_Ver10.otf

    - family: uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf

    - family: kufi
      fonts:
        - asset: assets/fonts/Kufam-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Kufam-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/Kufam-Regular.ttf
          weight: 100

    - family: naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
